# Site settings
title: A blog about Machine Learning
description: A blog about Machine Learning
baseurl: ""
url: "https://WhisperT.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Went Lee
user_description: A farmer in the field of AI
user_title: Beginner AI Researcher
email: went.lee@foxmail.com
github_username:  WhisperT


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About
    url: /about
plugins:
  - jekyll-feed

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
